version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.0.0-alpha-7-prerelease-20200921
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"

  selenium-hub:
    image: selenium/hub:4.0.0-alpha-7-prerelease-20200921
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - selenium-url=http://selenium-hub:4444
    links:
      - selenium-hub
    depends_on:
      - selenium-hub